// backend/models/user.model.js
import mongoose from "mongoose";
import bcrypt from "bcryptjs";

const userSchema = new mongoose.Schema({
    fullname: {
        type: String,
        required: true
    },
    email: {
        type: String,
        required: true,
        unique: true,
        lowercase: true, // Good practice for emails
        trim: true       // Good practice
    },
    phoneNumber: {
        type: String, // Store as String for flexibility with formats like +countrycode
        required: true
    },
    password: {
        type: String, // Storing plain text password - UNSAFE!
        required: true
    },
    role: {
        type: String,
        enum: ['student', 'recruiter'],
        required: true
    },
    profile: {
        bio: { type: String, default: '' },
        jobProfile: { type: String, default: '' },
        skills: [{ type: String }],
        resume: { type: String }, // Stores the filename generated by multer
        resumeOriginalName: { type: String }, // Stores the original uploaded filename
        company: { type: mongoose.Schema.Types.ObjectId, ref: 'Company' }, // Make sure you have a Company model if using this
        profilePhoto: { // Stores the filename for the profile photo
            type: String,
            default: ""
        }
    },
}, { timestamps: true });

// Hash password before saving
userSchema.pre('save', async function(next) {
    if (!this.isModified('password')) return next();
    
    try {
        const salt = await bcrypt.genSalt(10);
        this.password = await bcrypt.hash(this.password, salt);
        next();
    } catch (error) {
        next(error);
    }
});

// Method to compare password
userSchema.methods.comparePassword = async function(candidatePassword) {
    return bcrypt.compare(candidatePassword, this.password);
};

export const User = mongoose.model('User', userSchema);